# Generated by Django 4.0.2 on 2022-05-07 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_suggestionmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
